name: Release

on:
  push:
    branches:
      - master
      - master
    paths:
      - 'grpc/**/pb*.pb.go'
      - 'grpc-gateway/**/pb*.pb.go'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: cycjimmy/semantic-release-action@v3.1.1
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@5.0.0
            conventional-changelog-eslint@3.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    steps:
#      - uses: actions/checkout@master
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '16.x'
#      - run: npm ci
#      - run: npm run build --if-present
#      - run: npm test
#      - run: npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
